### ISSUE TITLE
[Task] Проверить все ли перенесли сюда из ПР Баси

### ISSUE THREAD

**Issue by AzzyDreemurr13** [qqqZXzz123/TauCetyBorgs#1]
Нужно сравнить код с этим ПРом на Тау https://github.com/TauCetiStation/TauCetiClassic/pull/11679 . Все ли мы оттуда перенесли и если нет, то добавить.

- [x] Борги научились открывать канистры
- [x] Джетпак доступен всем модулям боргов
- [x] Борги могут использовать вендоматы, где нет ценника
- [x] Лапки инженерного/научного это единое целое теперь
- [x] Модули получили все апгрейды которые хотели (Вплане там науч лента, hailer и так далее

**Comment by qqqZXzz123** [comment]
Сори, заметил твой вопрос сейчас. Вроде бы все твои правы есть в этом билде.
